name: hello-world
on:
  push:

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello prince!"
      - name: my-step2
        run: echo "ghumaw prince!"

  secondJob:
    runs-on: ubuntu-latest
    steps:
      - name: valo lage na
        run: echo "nomta boro udash"
      - name: Show commit SHA
        run: echo "Current commit SHA:" ${{ github.sha }}
      - name: Show branch SHA
        run: echo "Current commit SHA:" ${{ github.ref }}
