name: hello-world
'on': push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello prince!"
      - name: my-step2
        run: echo "ghumaw prince!"
  scondJob:
    runs-on: ubuntu-latest
    steps:
      - name: valo lage na
        run: echo "nomta boro udash"
