name: hello-world
on:
  push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Print Node Version
        run: echo "Testing Node.js ${{ matrix.node }}"
  
  inputs-job:
    runs-on: ubuntu-latest
    inputs:
      myInput:
        description: "An input"
        required: true
    steps:
      - run: echo "Input Value: ${{ inputs.myInput }}"
