name: hello-world
on:
  push:
  workflow_dispatch:
    inputs:
      myInput:
        description: "An input"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Print Node Version
        run: echo "Testing Node.js ${{ matrix.node }}"

  use-input:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Input Value: ${{ inputs.myInput }}"
