name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      myInput: "Hello from the main workflow!"
      myFlag: true
