name: Reusable Workflow

on:
  workflow_call:
    inputs:
      myInput:
        description: "A custom input message"
        required: true
        type: string
      myFlag:
        description: "A boolean flag"
        required: false
        type: boolean

jobs:
  show-input:
    runs-on: ubuntu-latest
    steps:
      - name: Display Input
        run: echo "The input provided is: ${{ inputs.myInput }}"
      - name: Check Flag
        if: ${{ inputs.myFlag == true }}
        run: echo "The flag is set to true!"
